version: "3.8"

services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    networks:
      - bde-network

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/bdemanager
      - PORT=3000
    depends_on:
      - mongo
    networks:
      - bde-network

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=bdemanager
    networks:
      - bde-network

volumes:
  mongo-data:

networks:
  bde-network:
    driver: bridge

